# Use a Python base image for scraper
FROM python:3.8-slim

WORKDIR /app


# Install the dependencies from the requirements file
RUN pip install --upgrade pip
RUN pip install flask 
RUN pip install psutil

# Copy the rest of the scraper code into the container
COPY scraper /app/scraper

# Default command to run the scraper
CMD ["python3", "/app/scraper/scraper.py"]
